name: Workflow

on:
  push
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Production deployment step
        run: echo "This is the production deployment workflow  🚀"
