name: Workflow

on:
  push:
    tags:
      - 'v*'
      
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Target deployment environment'
        required: true
        type: choice
        default: 'test'
        options:
          - dev
          - test
          - production
      tag_to_deploy:
        description: 'The tag version to deploy (e.g., v1.2.3)'
        required: true
        type: string 
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Production deployment step
        run: echo "This is the production deployment workflow  🚀"
